[build]
  command = "npm run build:deno"
  publish = ".dinou/dist3"
  edge_functions = "dinou/adapters/netlify-edge"

[build.environment]
  NODE_VERSION = "22"

[environment]
  NODE_ENV = "production"

[[edge_functions]]
  function = "netlify-edge"
  path = "/*"
  excludedPath = [
    "/assets/*",
    "/favicon.ico",
    "/*.ico",
    "/*.png",
    "/*.jpg",
    "/*.jpeg",
    "/*.svg",
    "/*.webp",
    "/*.webmanifest",
    "/*.txt",
    "/*.xml",
    "/*.map"
  ]
